version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: morgante/kafka
    build: .
    ports:
      - "9092:9092"
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  bash:
    image: wurstmeister/kafka
    links:
      - kafka
      - zookeeper
    command: /bin/bash
  manager:
    image: sheepkiller/kafka-manager
    ports:
      - "9000:9000"
    links:
      - kafka
      - zookeeper
    environment:
      ZK_HOSTS: zookeeper:2181